### PR TITLE
Extract filestack URL building into the filestack service

### PR DESCRIPTION
**Pull request by scudco**
We recently ran into an issue in which we needed to generate a filestack URL within a component. I extracted the main body of the `filestack-image` helper into the `filestack` service so that we can just inject the service and call `buildUrl`.

### CODE REVIEW

**Comment by mminkoff** [comment]
I don't have a strong objection to this but why not just call the helper from within your code?  That should be possible, shouldn't it?  This feels more like a helper thing than a service thing to me.

**Comment by sdhull** [comment]
@mminkoff lol that's exactly what I said but then @scudco reminded me we tried importing the helper and using it but it didn't work. The Ember `Helper` class appears to be dependent on rendering context or something, so using it in a route, controller or component js doesn't work.  [These stackoverflow answers](https://stackoverflow.com/questions/25107586/ember-js-use-handlebars-helper-inside-a-controller) recommend exporting a named function from the helper file, however in this case, using the service makes more sense IMO. 

Having the filestack service be the one-stop-shop for all filestack related stuff is appealing. Especially if we build new helpers, not having to worry about which helper you're importing is a win.

**Comment by scudco** [comment]
@mminkoff specifically, this is what we'd have to do. https://stackoverflow.com/a/42215744

So it's not the rendering context, but the fact that the `filestack-image` helper is not a purely functional helper meaning there is no method to export.

I imagine maybe the `filestack-image.js` could create an instance and also then export `compute`, but that'd be pretty weird imo.

**Comment by mminkoff** [comment]
:-) Well, you make a good point about the one-stop-shop.  I still believe there's a way to do it with a helper - I feel pretty confident I've done it before - but even still, it's obviously not, well, obvious, whereas it would be as part of the service.  OK, sold.

But - how about some documentation for this in the readme?  We still don't have any for the helper.

**Comment by sdhull** [comment]
definitely should add some docs to the readme :+1:

**Comment by scudco** [comment]
I can tighten this up with docs and migrating most of the helper tests to
service test file.

**Comment by scudco** [comment]
I'm closing this PR in favor of a new one focused on documentation and an entry point to API completeness for Filestack transformations.

I started to update the documentation, and then found myself needing to support more transformations in another project. I think the most important change coming out of all this no longer has much to do with this PR. I think what we want the most is _better documentation_, but that ultimately means a more complete interface that feels naturally connected to Filestack's API.

I will provide more information in the upcoming PR on how we can start chipping away at adding in first-class support for each transformation (i.e., you can't produce 400 errors with bad transformation options unless you intend to). We are already doing this with the `resize` transformation, but the new PR will create a pattern to isolate the building of a transformation.

**Comment by mminkoff** [comment]
@scudco thanks - sounds fantastic!  Looking forward to it.

**Pull request closed without merging**
