### PR TITLE
Filestack Transformations Support

### PR DESCRIPTION
**Pull request by scudco**
@mminkoff take a look at the [updated README.md](https://github.com/boundless-inc/ember-filestack/blob/filestack-transformation-support/README.md)

Here's what I've still got to do before I feel like this is mergeable:
* [x] Move tests into more accurate locations
  * Currently, everything is being tested via the handlebars helper
* [x] Add more information on what partial support of the `resize` transformation means
  * [ ] ~Consider adding "full support" for a transformation so we know what that could look like~
    * Will be addressed in a future PR
* [x] Add example of how to add first-class support for a transformation
  * Where does the code go? What does it take in? What does it spit out?
* [ ] ~Figure out how non-image transformations will work~
  * These are technically possible given the current API, but a future PR will add explicit support.
* [ ] ~Figure out if it's a good idea to extract the main content of `imageUrl` into a standalone class/object.~
  * This may be in a future PR.

### CODE REVIEW

**Comment by mminkoff** [comment]
I just made some minor edits to the readme - I hope you don't mind.

This looks great!  Perhaps add a note about welcoming pull requests with additional transformations?  I wouldn't want to hold up releasing this because not all the transformations are complete.

This is a terrific step forward - can't wait to get it out!

**Comment by scudco** [comment]
okay @mminkoff I think I feel good about this now that I've added service-specific tests and some more information in the README like you suggested. Please feel free to edit any of this as appropriate.

**Comment by scudco** [comment]
I'm not really happy about having to include `ember-assign-polyfill` as it's going to emit warnings for most users, but it gets the build working.

To remove the polyfill I think we'd have to do one of the following:
* change to a different method of doing what is `assign` is doing
* drop support for Ember <2.5
* conditionally include the polyfill somehow

What do you think @mminkoff?

**Comment by mminkoff** [comment]
@scudco how/where are we using assign?

**Comment by mminkoff** [comment]
@scudco I suppose it's better to simplify the legend like that, though there's something wrong - it's not completely done it seems.  Perhaps it could have a note at the top that some transformations have additional support code that helps ensure that parameters are used properly?

**Comment by scudco** [comment]
Yeah consider this still a WIP. I had to get to something else and wanted to commit what I had done. I need a way to point out that transformations may behave differently if noted without sounding really weird.

**Comment by scudco** [comment]
I added a couple sentences above table. I still think it sounds awkward, but at least that lone note next to `resize` isn't totally out of nowhere.

**Comment by mminkoff** [comment]
I tweaked it just a bit more and am comfortable (not to mention very excited) pushing this if you are @scudco.

**Comment by scudco** [comment]
yeah that looks great @mminkoff. thanks for adding clearer language :)

⛵️

**Pull request merged**
